---
# vim: sw=4 ts=102 ai
# tasks file for satellite
- name: ensure packages are updated
  yum:
    name: '*'
    state: latest
  notify: reboot host

- name: remove ntp
  yum:
    name: "ntp,ntpdate"
    state: absent

- name: install chrony
  yum:
    name: "chrony"
    state: present

- name: start chrony
  systemd:
    name: chronyd
    state: started
    enabled: yes

- name: Install Satellite packages
  yum:
    name: "{{ satellite_packages | join(',') }}"
    state: present

- name: "Patch foreman-installer https://github.com/theforeman/puppet-puppet/pull/613"
  patch:
    src: foreman-install.patch
    dest: /usr/share/foreman-installer/modules/puppet/manifests/server/passenger.pp

- name: "Copy foreman-installer needed files https://github.com/theforeman/puppet-puppet/pull/613"
  copy:
    dest: /usr/share/foreman-installer/modules/puppet/manifests/server/combine_certs.pp
    src: combine_certs.pp
