# vim: ts=2 sw=2 expandtab ai
---
- name: remove RHUI repos
  when:
    - ansible_pkg_mgr == 'yum'
    - subscription_org | length > 0
    - subscription_ak | length > 0
    - subscription_register
  yum:
    name: "{{ item }}"
    state: absent
  register: rhui_check
  with_items:
    - "rh-amazon-rhui-client*"

- name: clean yum cache
  file:
    state: absent
    path: "/var/cache/yum/{{ ansible_machine }}"
  when:
    - ansible_pkg_mgr == 'yum'
    - subscription_org | length > 0
    - subscription_ak | length > 0
    - subscription_register
    - rhui_check is changed

- name: enable RHEL product ID
  file:
    dest: /etc/yum/pluginconf.d/product-id.conf
    content: |
      [main]
      enabled=1
  when:
    - ansible_pkg_mgr == 'yum'
    - subscription_org | length > 0
    - subscription_ak | length > 0
    - subscription_register
    - rhui_check is changed

- name: register system
  redhat_subscription:
    state: present
    org_id: "{{ subscription_org }}"
    activationkey: "{{ subscription_ak }}"
  when:
    - subscription_org | length > 0
    - subscription_ak | length > 0
    - subscription_register

- name: enable repos
  subscription_repos:
    repos: "{{ subscription_repos }}"
  when:
    - ansible_pkg_mgr == 'yum'
    - subscription_register
